namespace TaylorSwift.Worksheets.Module_3
{
    internal class Worksheet3 : IActivity<decimal>
    {
        public string Title { get; } = "Worksheet 3.3 - Produce Number Sequence (reverse order)";
        public string Description { get; } = "Write a program which produces the given sequence numbers (in alternate arrangement and reverse order of the problem no. 2) using the three looping statements:\n\n5, 1, 4, 2, 3, 3, 2, 4, 1, 5,";
        public System.Collections.Generic.List<decimal> Inputs { get; set; } = new System.Collections.Generic.List<decimal>();
        public System.Collections.Generic.List<string> Output { get; set; } = new System.Collections.Generic.List<string>();

        public void Operation()
        {
            Output.Clear();

            // The sequence is generated by iterating i from 1 to 5, and outputting (6 - i), followed by i.

            // --- 1. FOR Loop Implementation ---
            Output.Add("--- FOR Loop Results ---");
            System.String resultFor = "";
            for (int i = 1; i <= 5; i++)
            {
                // Concatenates the inverse (6-i) and the current number (i)
                resultFor += (6 - i).ToString() + ", " + i.ToString() + ", ";
            }
            Output.Add($"Sequence: {resultFor}");

            // --- 2. WHILE Loop Implementation ---
            Output.Add("\n--- WHILE Loop Results ---");
            System.String resultWhile = "";
            int j = 1;
            while (j <= 5)
            {
                // Concatenates the inverse (6-j) and the current number (j)
                resultWhile += (6 - j).ToString() + ", " + j.ToString() + ", ";
                j++;
            }
            Output.Add($"Sequence: {resultWhile}");

            // --- 3. DO-WHILE Loop Implementation ---
            Output.Add("\n--- DO-WHILE Loop Results ---");
            System.String resultDoWhile = "";
            int k = 1;
            do
            {
                // Concatenates the inverse (6-k) and the current number (k)
                resultDoWhile += (6 - k).ToString() + ", " + k.ToString() + ", ";
                k++;
            }
            while (k <= 5);
            Output.Add($"Sequence: {resultDoWhile}");
        }

        public void Execute()
        {
            System.Console.Clear();
            System.Console.ResetColor();

            System.Console.ForegroundColor = System.ConsoleColor.Cyan;
            System.Console.WriteLine(Title);
            System.Console.ForegroundColor = System.ConsoleColor.Yellow;
            System.Console.WriteLine(Description);
            System.Console.WriteLine();

            Output.Clear();
            Inputs.Clear();

            Operation();

            foreach (var line in Output)
                System.Console.WriteLine(line);

            System.Console.ForegroundColor = System.ConsoleColor.Red;
            System.Console.WriteLine("\nPress any key to go back...");
            System.Console.ReadKey(true);
            System.Console.ResetColor();
        }
    }
}
